<script setup lang="ts">
import { computed, ref } from 'vue'
import { anatomyIndex } from '~/data/ocularTree'
import { useExplorerStore } from '~/stores/explorer'

const route = useRoute()
const store = useExplorerStore()
const copy = computed(() => store.language === 'ar')
const text = (ar: string, en: string) => copy.value ? ar : en
const part = computed(() => anatomyIndex[String(route.params.id)] || anatomyIndex.sclera)
const posteriorIds = ['retina', 'macula', 'fovea', 'faz', 'opticDisc', 'opticCup', 'neuroretinalRim', 'rpe', 'rpeCells', 'photoreceptors', 'rodsCones', 'elm', 'onl', 'opl', 'inl', 'ipl', 'gcl', 'ganglionCells', 'nfl', 'ilm', 'retinalVessels', 'superficialPlexus', 'deepPlexus', 'choroid', 'hallerLayer', 'sattlerLayer', 'choriocapillaris', 'bruchsMembrane']
const anteriorIds = ['cornea', 'cornealEpithelium', 'bowmanLayer', 'cornealStroma', 'descemetMembrane', 'cornealEndothelium', 'iris', 'irisStroma', 'sphincterPupillae', 'dilatorPupillae', 'pupil', 'ciliary', 'parsPlicata', 'parsPlana', 'ciliaryMuscle', 'zonules', 'lens', 'lensCapsule', 'lensCortex', 'lensNucleus']
const orbitalIds = ['superiorRectus', 'lateralRectus', 'orbitalFat', 'orbitalBone', 'ophthalmicArtery']
const focusClass = computed(() => posteriorIds.includes(part.value.id) ? 'diagram-posterior' : anteriorIds.includes(part.value.id) ? 'diagram-anterior' : orbitalIds.includes(part.value.id) ? 'diagram-orbit' : part.value.id === 'opticNerve' || part.value.id === 'laminaCribrosa' || part.value.id === 'opticNerveSheath' || part.value.id === 'opticChiasm' ? 'diagram-nerve' : part.value.id === 'sclera' || part.value.id === 'episclera' || part.value.id === 'scleralStroma' || part.value.id === 'laminaFusca' ? 'diagram-sclera' : 'diagram-central')
const activeImaging = ref<string | null>(null)
const usesLocalAtlasPlate = computed(() => anteriorIds.includes(part.value.id) || ['aqueousSystem', 'conjunctiva', 'lacrimalApparatus'].includes(part.value.id))
const componentImage = computed(() => posteriorIds.includes(part.value.id) || part.value.id === 'vitreous' || part.value.id === 'vitreousCortex' || part.value.id === 'posteriorHyaloid' ? '/anatomy/fundus-clinical.png' : orbitalIds.includes(part.value.id) || part.value.id === 'muscles' || part.value.id === 'opticNerve' || part.value.id === 'opticNerveSheath' || part.value.id === 'chiasm' ? '/anatomy/orbital-cutaway.png' : usesLocalAtlasPlate.value ? '/anatomy/anterior-segment-atlas.png' : '/anatomy/eye-diagram-wikimedia.png')
const imagingInfo = computed(() => {
  const modality = activeImaging.value || ''
  const definitions: Record<string, [string, string]> = {
    'OCT': ['التصوير المقطعي البصري (OCT) يعطي مقطعاً عالي الدقة عبر طبقات العين. يُستخدم هنا لربط '+part.value.arabic+' بموقعه الطبقي ومراقبة أي تغير بنيوي.', 'Optical coherence tomography (OCT) provides a high-resolution cross-section through ocular layers. Here it localises '+part.value.name+' and monitors structural change.'],
    'OCT-A': ['تصوير الأوعية بالمقطع البصري (OCT-A) يرسم تدفق الدم دون صبغة. يفيد في دراسة الشبكات الدقيقة المرتبطة بـ '+part.value.arabic+'.', 'OCT angiography (OCT-A) maps blood flow without dye and is useful for studying the microvascular networks related to '+part.value.name+'.'],
    'FA': ['تصوير الأوعية بالفلوريسين (FA) يتابع مرور الصبغة داخل أوعية قاع العين، ويُستخدم لتقييم الامتلاء أو التسرب أو مناطق نقص التروية.', 'Fluorescein angiography (FA) follows dye through fundus vessels to assess filling, leakage, and non-perfusion.'],
    'ICG': ['تصوير الأوعية بالإندوسيانين الأخضر (ICG) يستخدم ضوءاً تحت أحمر ويُظهر الدورة الدموية المشيمية بوضوح أكبر.', 'Indocyanine-green angiography (ICG) uses near-infrared light and better demonstrates choroidal circulation.'],
    'FAF': ['التألّق الذاتي لقاع العين (FAF) يرصد الإشارات المرتبطة بالليبوفيوسين في الظهارة الصبغية للشبكية، لذلك يوضح النشاط أو الضمور في الأنسجة الخلفية.', 'Fundus autofluorescence (FAF) records lipofuscin-related signals in retinal pigment epithelium and helps show activity or atrophy in posterior tissues.'],
    'B-scan': ['الموجات فوق الصوتية B-scan تُظهر بنية العين عندما تمنع عتامة الوسط رؤية القاع، وتساعد في تقييم الجسم الزجاجي والشبكية والجدار الخلفي.', 'B-scan ultrasonography displays ocular structure when media opacity blocks the fundus view and assists with vitreous, retinal, and posterior-wall assessment.'],
    'Ultrasound B-scan': ['الموجات فوق الصوتية B-scan تُظهر بنية العين عندما تمنع عتامة الوسط رؤية القاع، وتساعد في تقييم الجسم الزجاجي والشبكية والجدار الخلفي.', 'B-scan ultrasonography displays ocular structure when media opacity blocks the fundus view and assists with vitreous, retinal, and posterior-wall assessment.'],
    'Ultrasound biomicroscopy': ['التصوير بالموجات فوق الصوتية عالية التردد يوضح تراكيب الجزء الأمامي التي لا تظهر بوضوح خلف القزحية، مثل الجسم الهدبي والألياف الزنارية.', 'Ultrasound biomicroscopy uses high-frequency ultrasound to show anterior structures hidden behind the iris, including the ciliary body and zonules.']
  }
  const content = definitions[modality] || ['هذه الوسيلة تُستخدم في سياق '+part.value.arabic+' لتجميع المعلومات التشريحية والوظيفية والسريرية دون مغادرة الأطلس.', 'This modality is used in the context of '+part.value.name+' to combine anatomical, functional, and clinical information without leaving the atlas.']
  return { title: modality, body: copy.value ? content[0] : content[1] }
})
const clinicalCaption = computed(() => copy.value
  ? 'موضع '+part.value.arabic+' في رسم تشريحي مرخّص ومركّز على البنية المختارة'
  : 'Position of '+part.value.name+' in a licensed anatomical diagram focused on the selected structure')
const expanded = computed(() => copy.value ? {
  location: ['يقع '+part.value.arabic+' ضمن منظومة مترابطة؛ '+part.value.location, 'تُفسَّر العلامات في هذا الموضع دائماً مع البنى الأمامية والخلفية والمجاورة، لا كعنصر معزول.', 'في الامتحان العملي: حدّد الاتجاه والمجاورات أولاً، ثم اربطها بالوظيفة أو المسار التشريحي ذي الصلة.', 'فكّر في هذا الموضع على أنه نقطة اتصال: قد تُحيل شكوى واحدة إلى هذا النسيج أو إلى بنية مجاورة، لذلك يفيد فحص العين المقابل دائماً في المقارنة.', 'أثناء وصفه تشريحياً، استخدم نقطة مرجعية ثابتة مثل القرنية أو القرص البصري أو الحافة الحجاجية ثم اتبع العلاقة في ثلاثة أبعاد.'],
  function: ['الدور الأساسي هو: '+part.value.function, 'تظهر أهميته عملياً عند ربط الفحص السريري بالوظيفة البصرية أو الحركية أو الوعائية التي يشارك فيها.', 'عند المراجعة الشفوية، اشرح الآلية الطبيعية أولاً ثم اذكر كيف ينعكس اختلالها على الشكوى أو علامة الفحص.', 'ابدأ دائماً بالوظيفة الطبيعية قبل تسمية المرض: هذا يوضح سبب اختيار اختبار محدد، ولماذا ترتبط العلامة السريرية بهذا الجزء تحديداً.', 'يمكن تقييم الأثر الوظيفي من خلال حدة الإبصار أو المجال البصري أو حركات العين أو المظهر في المصباح الشقي والتصوير، بحسب موضع البنية.'],
  histology: [part.value.histology, 'هذا التنظيم المجهري يفسر لماذا تختلف الاستجابة للإصابة أو الالتهاب أو الإجهاد الميكانيكي من طبقة إلى أخرى.', 'اربط نوع الخلية أو النسيج بالحاجز أو الشفافية أو النقل العصبي أو الدعم الميكانيكي الذي يقدمه، ثم اذكر وسيلة فحص مناسبة له.', 'التفريق بين الطبقات مهم لأن الأمراض لا تصيب جميعها في العمق نفسه؛ قد يبدو السطح سليماً بينما يكشف التصوير تغيراً في طبقة أعمق.', 'في السؤال العملي، اربط الاسم النسيجي بالمظهر المتوقع: شفافية أو صبغة أو تروية أو ألياف أو خلايا عصبية، ثم اذكر ما الذي سيغيّره الالتهاب أو التندّب.'],
  damage: [part.value.damage, 'قد يبدأ الخلل بعرض وظيفي أو تغير في الفحص قبل أن يظهر بصورة واضحة في التصوير، لذلك تهم المقارنة بين العينين والسياق السريري.', 'قبل الوصول إلى تفسير أو خطة علاجية، قارن الأعراض والفحص والتصوير المناسب، وحدد العلامات التي تستدعي تقييماً عاجلاً.', 'اربط الزمن بالخطورة: التدهور المفاجئ أو الألم الشديد أو فقد الرؤية أو العلامات العصبية يستدعي تقييماً عاجلاً ولا يفسّر بالتشريح وحده.', 'للمراجعة التعليمية، لخّص الحالة في أربع نقاط: العرض، البنية المصابة، الاختبار أو التصوير الذي يوضّحها، والخطوة السريرية الآمنة التالية.']
} : {
  location: [part.value.name+' belongs to an integrated system. '+part.value.location, 'Interpret findings at this location with anterior, posterior, and adjacent structures rather than as an isolated element.', 'For a practical examination, establish orientation and relations first, then connect them to the relevant function or anatomical pathway.', 'Treat this location as a junction: a single symptom can arise from this tissue or an adjacent structure, so comparison with the fellow eye is valuable.', 'When describing it anatomically, begin with a stable landmark such as the cornea, optic disc, or orbital rim, then follow the relation in three dimensions.'],
  function: ['Its primary role is: '+part.value.function, 'Its practical importance becomes clear when clinical examination is linked with the visual, motor, or vascular function it supports.', 'For an oral answer, explain the normal mechanism first, then state how dysfunction changes symptoms or examination findings.', 'Start with normal physiology before naming disease. This clarifies why a particular test is chosen and why a clinical sign belongs to this structure.', 'Functional impact can be assessed with visual acuity, visual fields, ocular movements, slit-lamp appearance, or imaging, depending on the structure’s location.'],
  histology: [part.value.histology, 'This microscopic organisation explains why injury, inflammation, and mechanical stress can affect each layer differently.', 'Link the cell or tissue type to the barrier, transparency, neural transmission, or mechanical support it provides, then name a suitable examination method.', 'Layer-level localisation matters because disease does not affect every depth equally; the surface may appear preserved while imaging reveals a deeper change.', 'For a practical answer, connect the histologic name to an expected appearance—transparency, pigment, perfusion, fibres, or neural cells—then state what inflammation or scarring would alter.'],
  damage: [part.value.damage, 'Dysfunction may first present as a functional symptom or examination change before imaging becomes clearly abnormal, so compare both eyes and the clinical context.', 'Before reaching an interpretation or treatment plan, compare symptoms, examination, and suitable imaging, and identify red flags that require urgent assessment.', 'Link timing to urgency: sudden deterioration, severe pain, vision loss, or neurological signs require urgent assessment and cannot be explained by anatomy alone.', 'For study, summarise each condition in four steps: the symptom, the affected structure, the examination or imaging that demonstrates it, and the safe next clinical action.']
})
</script>

<template>
  <main class="detail-page" :dir="copy ? 'rtl' : 'ltr'">
    <header class="detail-nav"><NuxtLink to="/">{{text('→ العودة إلى الأطلس','← Back to atlas')}}</NuxtLink><div class="detail-actions"><span>ATLAS / {{ part.latin }}</span><button class="language-toggle" @click="store.language=copy?'en':'ar'">{{copy?'EN':'ع'}}</button></div></header>
    <section class="detail-title"><div><p>STRUCTURE DOSSIER</p><h1>{{copy?part.arabic:part.name}}</h1><span>{{part.name}} · {{part.latin}}</span></div></section>
    <section class="anatomy-gallery anatomy-gallery--single">
      <figure class="anatomy-plate clinical-plate selected-structure-image"><img :src="componentImage" :class="focusClass" :alt="'Anatomical diagram focused on '+part.name"><figcaption>{{clinicalCaption}} · <span v-if="usesLocalAtlasPlate">{{text('لوحة تشريحية تعليمية محلية للأطلس','Local educational atlas plate')}}</span><a v-else href="https://commons.wikimedia.org/wiki/File:Eye-diagram_no_circles_border.svg" target="_blank" rel="noreferrer">Chabacano / Wikimedia Commons · CC BY-SA 3.0</a></figcaption></figure>
    </section>
    <section class="detail-grid">
      <article><small>LOCATION</small><h2>{{text('الموقع والمجاورات','Location & relations')}}</h2><p v-for="paragraph in expanded.location" :key="paragraph" class="detail-secondary">{{paragraph}}</p></article>
      <article><small>FUNCTION</small><h2>{{text('الوظيفة','Function')}}</h2><p v-for="paragraph in expanded.function" :key="paragraph" class="detail-secondary">{{paragraph}}</p></article>
      <article><small>HISTOLOGY</small><h2>{{text('التركيب النسيجي','Histology')}}</h2><p v-for="paragraph in expanded.histology" :key="paragraph" class="detail-secondary">{{paragraph}}</p></article>
      <article class="warning-card"><small>IF DAMAGED</small><h2>{{text('عند التلف','If damaged')}}</h2><p v-for="paragraph in expanded.damage" :key="paragraph" class="detail-secondary">{{paragraph}}</p></article>
    </section>
    <section class="related-grid">
      <article><small>DIAGNOSTIC IMAGING</small><h2>{{text('التصوير المرتبط','Related imaging')}}</h2><div class="tag-list"><button v-for="item in part.imaging" :key="item" type="button" @click="activeImaging=item">{{item}} <span aria-hidden="true">ⓘ</span></button></div><p>{{text('اضغط على أي اختصار أو اسم وسيلة تصوير لعرض شرحها داخل الأطلس.','Select any abbreviation or imaging name to read its explanation inside the atlas.')}}</p></article>
      <article><small>CONDITIONS</small><h2>{{text('الحالات المرتبطة','Related conditions')}}</h2><div class="tag-list disease-tags"><span v-for="item in part.diseases" :key="item">{{item}}</span></div><p>{{part.clinical}}</p></article>
      <article><small>PROCEDURES</small><h2>{{text('التدخلات ذات الصلة','Related procedures')}}</h2><div class="tag-list procedure-tags"><span v-for="item in part.procedures" :key="item">{{item}}</span></div><p>{{text('يستخدم هذا القسم للمراجعة التشريحية قبل التعلم السريري أو الجراحي.','Use this section for anatomical review before clinical or surgical learning.')}}</p></article>
    </section>
    <footer class="detail-reference"><span>⌁</span><div><b>{{text('مرجع قابل للتتبع','Traceable reference')}}</b><p>{{part.reference}}</p><small>{{text('آخر مراجعة: ','Last reviewed: ')}}{{part.reviewed}}</small></div></footer>
    <Teleport to="body"><div v-if="activeImaging" class="imaging-overlay" role="presentation" @click.self="activeImaging=null"><section class="imaging-popover" role="dialog" aria-modal="true" :aria-label="imagingInfo.title"><button class="popover-close" type="button" :aria-label="text('إغلاق','Close')" @click="activeImaging=null">×</button><small>{{text('وسيلة التصوير','IMAGING MODALITY')}}</small><h2>{{imagingInfo.title}}</h2><p>{{imagingInfo.body}}</p><div><span>{{text('السياق التشريحي','ANATOMICAL CONTEXT')}}</span><b>{{copy?part.arabic:part.name}}</b></div></section></div></Teleport>
  </main>
</template>

<style scoped>
.detail-actions{display:flex;align-items:center;gap:12px}.language-toggle{border:1px solid #31546e;background:#102d43;color:#dffaf7;border-radius:6px;padding:6px 9px;font-weight:700}.imaging-overlay{position:fixed;inset:0;z-index:50;display:grid;place-items:center;padding:20px;background:rgba(1,5,10,.72);backdrop-filter:blur(8px)}.imaging-popover{position:relative;width:min(540px,100%);border:1px solid #3a7180;border-radius:16px;padding:28px;background:linear-gradient(145deg,#10263a,#07121e);color:#e9f5fb;box-shadow:0 24px 80px rgba(0,0,0,.55)}.imaging-popover small,.imaging-popover div span{color:#82dfd0;font-size:.74rem;font-weight:800;letter-spacing:.14em}.imaging-popover h2{margin:10px 0 12px;font-size:1.65rem}.imaging-popover p{margin:0;color:#cbdce7;font-size:1.05rem;line-height:1.8}.imaging-popover div{display:flex;justify-content:space-between;gap:14px;align-items:center;margin-top:22px;padding-top:18px;border-top:1px solid #2b4b62}.imaging-popover div b{font-size:.95rem}.popover-close{position:absolute;top:12px;inset-inline-end:12px;width:32px;height:32px;border:1px solid #40647a;border-radius:50%;background:#132c40;color:#dffaf7;font-size:22px;line-height:1}
</style>
